/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type TalaDBNode = TalaDbNode
export declare class TalaDbNode {
  /** Open an in-memory database (useful for testing). */
  static openInMemory(): TalaDbNode
  /**
   * Open a file-backed database at the given path.
   *
   * `config_json` is an optional JSON-serialised `TalaDbConfig`; only its
   * `durability` block is read here. Change webhooks are delivered by the
   * `taladb` TypeScript client, not by this binding.
   */
  static open(path: string, configJson?: string | undefined | null, passphrase?: string | undefined | null): TalaDbNode
  /**
   * Force any batched (eventual-durability) writes to disk. No-op under the
   * default immediate durability. Backs `db.flush()`.
   */
  flush(): void
  /**
   * Compact the underlying storage file, reclaiming space freed by deletes
   * and updates. Call during idle periods after large bulk deletes.
   * Returns the number of bytes reclaimed (may be 0).
   */
  compact(): void
  /**
   * Close the database, releasing the file handle and its lock.
   *
   * Subsequent calls on this object return an error. Collections obtained
   * before `close()` keep the underlying storage alive until they are
   * garbage-collected — drop them too to fully release the file.
   */
  close(): void
  /** List user collection names (excludes reserved `_`-prefixed collections). */
  listCollectionNames(): Array<string>
  /**
   * Read the current application migration version (0 if never set). Backs
   * the `openDB({ migrations })` runner, which advances it per migration.
   */
  userVersion(): number
  /**
   * Persist the application migration version. Called after each migration's
   * body succeeds so a crash mid-run resumes from the last applied version.
   */
  setUserVersion(version: number): void
  /** Get a collection by name. */
  collection(name: string): CollectionNode
}
export declare class CollectionNode {
  /** Insert a document. Returns the ULID string id. */
  insert(doc: JsonValue): string
  /** Insert multiple documents. */
  insertMany(docs: Array<JsonValue>): Array<string>
  /** Find documents matching the filter. */
  find(filter: JsonValue): Array<JsonValue>
  /** Find a single document or return null. */
  findOne(filter: JsonValue): JsonValue | null
  /**
   * Run a MongoDB-style aggregation pipeline. `pipeline` is a JSON array of
   * stage objects (`$match`, `$group`, `$sort`, `$skip`, `$limit`,
   * `$project`). Returns the resulting documents.
   */
  aggregate(pipeline: JsonValue): Array<JsonValue>
  /** Update the first matching document. */
  updateOne(filter: JsonValue, update: JsonValue): boolean
  /** Update all matching documents. */
  updateMany(filter: JsonValue, update: JsonValue): number
  /** Delete the first matching document. */
  deleteOne(filter: JsonValue): boolean
  /** Delete all matching documents. */
  deleteMany(filter: JsonValue): number
  /** Count documents matching the filter. */
  count(filter: JsonValue): number
  /** Create a secondary index on a field. */
  createIndex(field: string): void
  /** Drop a secondary index. */
  dropIndex(field: string): void
  /** Create a compound (multi-field) index over an ordered list of fields. */
  createCompoundIndex(fields: Array<string>): void
  /** Drop a compound index by its ordered field list. */
  dropCompoundIndex(fields: Array<string>): void
  /**
   * Create a vector index on `field`.
   *
   * - `metric` — optional: `"cosine"` (default), `"dot"`, or `"euclidean"`.
   * - `index_type` — optional: `"flat"` (default) or `"hnsw"`.
   * - `hnsw_m` — HNSW connectivity (default 16).
   * - `hnsw_ef_construction` — build quality (default 200).
   */
  createVectorIndex(field: string, dimensions: number, metric?: string | undefined | null, indexType?: string | undefined | null, hnswM?: number | undefined | null, hnswEfConstruction?: number | undefined | null): void
  /** Drop a vector index (and its HNSW graph if present). */
  dropVectorIndex(field: string): void
  /**
   * Rebuild the HNSW graph for a vector index from the current flat data.
   * No-op when the feature is disabled or the index is flat-only.
   */
  upgradeVectorIndex(field: string): void
  /**
   * Return the indexes on this collection as a JSON string
   * `{ btree: string[], fts: string[], vector: string[] }`.
   */
  listIndexes(): string
  /** Create a full-text search index on a string field. */
  createFtsIndex(field: string): void
  /** Drop a full-text search index and everything it stores. */
  dropFtsIndex(field: string): void
  /**
   * Rank documents against a free-text query using BM25.
   *
   * Unlike the `$contains` filter, which requires every token, this uses
   * OR semantics — matching more query terms simply scores higher.
   *
   * Returns an array of `{ document: {...}, score: number }` objects.
   */
  searchText(field: string, query: string, topK: number, filter?: JsonValue | undefined | null, options?: JsonValue | undefined | null): Array<JsonValue>
  /**
   * Hybrid retrieval — BM25 and vector similarity fused with reciprocal
   * rank fusion.
   *
   * `options` accepts `{ rrfK, textWeight, vectorWeight, candidates, k1, b }`.
   * Returns `{ document, score, textRank, vectorRank }`, where the ranks are
   * zero-based positions in each retriever's list or `null` if that
   * retriever did not return the document.
   */
  hybridSearch(textField: string, text: string, vectorField: string, vector: Array<number>, topK: number, filter?: JsonValue | undefined | null, options?: JsonValue | undefined | null): Array<JsonValue>
  /**
   * Find the `top_k` nearest documents to `query`.
   *
   * `filter` — optional pre-filter in the same JSON object format as `find`.
   *
   * Returns an array of `{ document: {...}, score: number }` objects.
   */
  findNearest(field: string, query: Array<number>, topK: number, filter?: JsonValue | undefined | null): Array<JsonValue>
  /**
   * Zero-copy Float32Array fast path. Avoids the f64→f32 conversion loop
   * used by `findNearest(number[])`, which matters for large embeddings
   * (768/1024/1536 dims) called on the hot path.
   */
  findNearestF32(field: string, query: Float32Array, topK: number, filter?: JsonValue | undefined | null): Array<JsonValue>
  /**
   * Async variant of `findNearest` — runs on the libuv thread pool so large
   * scans or unfiltered HNSW queries don't block the JS thread. Accepts a
   * `Float32Array` for zero-copy embedding transfer.
   */
  findNearestAsync(field: string, query: Float32Array, topK: number, filter?: JsonValue | undefined | null): Promise<Array<any>>
  /**
   * Async variant of `find` — runs on the libuv thread pool so large
   * collection scans don't block the JS thread.
   */
  findAsync(filter: JsonValue): Promise<Array<any>>
  /**
   * Async variant of `insert` — the write runs on the libuv thread pool
   * instead of blocking the JS thread.
   */
  insertAsync(doc: JsonValue): Promise<string>
  /** Async variant of `insertMany`. */
  insertManyAsync(docs: Array<JsonValue>): Promise<Array<string>>
  /** Async variant of `updateOne`. */
  updateOneAsync(filter: JsonValue, update: JsonValue): Promise<boolean>
  /** Async variant of `updateMany`. */
  updateManyAsync(filter: JsonValue, update: JsonValue): Promise<number>
  /** Async variant of `deleteOne`. */
  deleteOneAsync(filter: JsonValue): Promise<boolean>
  /** Async variant of `deleteMany`. */
  deleteManyAsync(filter: JsonValue): Promise<number>
}
